/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppWrapUpRouteImport } from './routes/_app.wrap-up'
import { Route as AppTodayRouteImport } from './routes/_app.today'
import { Route as AppQuestionsRouteImport } from './routes/_app.questions'
import { Route as AppHealthRouteImport } from './routes/_app.health'
import { Route as AppDecisionsRouteImport } from './routes/_app.decisions'
import { Route as AppBacklogRouteImport } from './routes/_app.backlog'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWrapUpRoute = AppWrapUpRouteImport.update({
  id: '/wrap-up',
  path: '/wrap-up',
  getParentRoute: () => AppRoute,
} as any)
const AppTodayRoute = AppTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AppRoute,
} as any)
const AppQuestionsRoute = AppQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => AppRoute,
} as any)
const AppHealthRoute = AppHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AppRoute,
} as any)
const AppDecisionsRoute = AppDecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => AppRoute,
} as any)
const AppBacklogRoute = AppBacklogRouteImport.update({
  id: '/backlog',
  path: '/backlog',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/onboarding': typeof OnboardingRoute
  '/backlog': typeof AppBacklogRoute
  '/decisions': typeof AppDecisionsRoute
  '/health': typeof AppHealthRoute
  '/questions': typeof AppQuestionsRoute
  '/today': typeof AppTodayRoute
  '/wrap-up': typeof AppWrapUpRoute
}
export interface FileRoutesByTo {
  '/onboarding': typeof OnboardingRoute
  '/backlog': typeof AppBacklogRoute
  '/decisions': typeof AppDecisionsRoute
  '/health': typeof AppHealthRoute
  '/questions': typeof AppQuestionsRoute
  '/today': typeof AppTodayRoute
  '/wrap-up': typeof AppWrapUpRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/_app/backlog': typeof AppBacklogRoute
  '/_app/decisions': typeof AppDecisionsRoute
  '/_app/health': typeof AppHealthRoute
  '/_app/questions': typeof AppQuestionsRoute
  '/_app/today': typeof AppTodayRoute
  '/_app/wrap-up': typeof AppWrapUpRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/backlog'
    | '/decisions'
    | '/health'
    | '/questions'
    | '/today'
    | '/wrap-up'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/onboarding'
    | '/backlog'
    | '/decisions'
    | '/health'
    | '/questions'
    | '/today'
    | '/wrap-up'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/onboarding'
    | '/_app/backlog'
    | '/_app/decisions'
    | '/_app/health'
    | '/_app/questions'
    | '/_app/today'
    | '/_app/wrap-up'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wrap-up': {
      id: '/_app/wrap-up'
      path: '/wrap-up'
      fullPath: '/wrap-up'
      preLoaderRoute: typeof AppWrapUpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/today': {
      id: '/_app/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AppTodayRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/questions': {
      id: '/_app/questions'
      path: '/questions'
      fullPath: '/questions'
      preLoaderRoute: typeof AppQuestionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/health': {
      id: '/_app/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof AppHealthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/decisions': {
      id: '/_app/decisions'
      path: '/decisions'
      fullPath: '/decisions'
      preLoaderRoute: typeof AppDecisionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/backlog': {
      id: '/_app/backlog'
      path: '/backlog'
      fullPath: '/backlog'
      preLoaderRoute: typeof AppBacklogRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBacklogRoute: typeof AppBacklogRoute
  AppDecisionsRoute: typeof AppDecisionsRoute
  AppHealthRoute: typeof AppHealthRoute
  AppQuestionsRoute: typeof AppQuestionsRoute
  AppTodayRoute: typeof AppTodayRoute
  AppWrapUpRoute: typeof AppWrapUpRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBacklogRoute: AppBacklogRoute,
  AppDecisionsRoute: AppDecisionsRoute,
  AppHealthRoute: AppHealthRoute,
  AppQuestionsRoute: AppQuestionsRoute,
  AppTodayRoute: AppTodayRoute,
  AppWrapUpRoute: AppWrapUpRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
